Update Imperium - Grey Knights.cat - Fix Typos
BSData/wh40k-9e pull request #11731
Opened 2022-07-29 15:53 UTC by PappyJLoco

Closed the previous Pull Req. 

Fixing some typos in the document.

2022-07-29 15:54 UTC, PappyJLoco commented
@Mad-Spy Tagged you in for sight on this as I closed the other Pull Req. 

Reverted the changes and have opted to fix some more obvious typos.

2022-07-29 23:23 UTC, Mad-Spy requested changes
Please increment the file version

2022-07-30 06:32 UTC, PappyJLoco commented
> Please increment the file version

See amended to 112.

Thanks

2022-07-31 15:33 UTC, Mad-Spy approved these changes

2022-07-31 15:34 UTC, merged