Fix: Typos and Grammar errors
BSData/wh40k-9e pull request #8124
Opened 2020-09-16 16:09 UTC by PixelTom

Fixes a large number of typos and grammar issues.

2020-09-16 16:36 UTC, amis92 requested changes
It looks great with a few little mistakes.

2020-09-16 16:36 UTC, amis92 commented on Chaos - FW Renegade and Heretics.cat
> -                    <characteristic name="Abilities" typeId="837d-5e63-aeb7-1410">Reroll failed wound rolls on &lt;VEHICLE&gt;</characteristic>
It looks like casing got lost here - can you fix that?

2020-09-16 16:36 UTC, amis92 commented on Chaos - FW Renegade and Heretics.cat
> -                    <characteristic name="Abilities" typeId="837d-5e63-aeb7-1410">Reroll failed wound rolls on Non - &lt;VEHICLE&gt; models</characteristic>
It looks like casing got lost here - can you fix that?

2020-09-16 16:36 UTC, amis92 commented on Chaos - FW Renegade and Heretics.cat
> +            <characteristic name="Description" typeId="21befb24-fc85-4f52-a745-64b2e48f8228">An earthshaker Carriage Battery can only fire its ranged weapon if a friendly &lt;RENEGADE&gt; guardsman c
It looks like casing got lost here - can you fix that?

2020-09-16 16:36 UTC, amis92 commented on Chaos - FW Renegade and Heretics.cat
> +            <characteristic name="Abilities" typeId="837d-5e63-aeb7-1410">re-roll failed wound rolls on &lt;VEHICLE&gt;</characteristic>
It looks like casing got lost here - can you fix that?

2020-09-16 16:36 UTC, amis92 commented on Imperium - Astra Militarum - Library.cat
> +        <profile id="1fc8-b024-e2a1-0dff" name="separate Orders" hidden="false" typeId="72c5eafc-75bf-4ed9-b425-78009f1efe82" typeName="Abilities">
It looks like casing got lost here - can you fix that?

2020-09-16 16:36 UTC, amis92 commented on Imperium - Grey Knights.cat
> +        <characteristic name="Details" typeId="ad96-dfa4-b4ed-656d">Ethereal Manipulation has a warp charge value of 7. If manifested, select one friendly GREY KNIGHTS unit within 6&quot; of this psy
It looks like casing got lost here - can you fix that?

2020-09-16 16:41 UTC, amis92 commented
@PixelTom We appreciate the changes.

This PR is huge however, and would benefit from being split into multiples.

Another reason is that this PR involves almost whole team to sign-off, and if you split the file changes into separate PRs it'd be much easier and faster to accept.

2020-09-16 22:09 UTC, PixelTom commented
@amis92 thanks for the feedback! I can close this PR and make 1 for each file if you'd like.

2020-09-17 03:24 UTC, PixelTom commented
Closing this. Will update description with the new PRs as I make them.

2020-09-17 03:24 UTC, closed without merging